from docx import Document

# Create a new Document
doc = Document()

# Add a heading
doc.add_heading('Sample Questions', level=1)

# Add questions to the document
questions = [
    "26. Match List-I with List-II and select the correct answer using the codes given below the lists: [1998]",
    "List-I (years)               List-II (events)",
    "A. 1556                      1. Battle of Haldi Ghati",
    "B. 1600                      2. Nadir Shah's capture of Delhi",
    "C. 1686                      3. Death of Shivaji",
    "D. 1739                      4. Grant of Charter to East India Company",
    "Codes: A B C D",
    "(a) A – 3; B – 4; C – 2; D – 1",
    "(b) A – 1; B – 4; C – 3; D – 2",
    "(c) A – 4; B – 3; C – 2; D – 1",
    "(d) A – 1; B – 2; C – 3; D – 4",
    "U.P .P .C.S. (Mains) 2010",
    "Answer - (d)",
    "",
    "27. Please examine the combination of the following Lists and accordingly select the correct Code: [1988]",
    "List-I (crop)     List-II (state)",
    "A. Groundnut   1. Andhra Pradesh",
    "B. Mustard        2. Rajasthan",
    "C. Soyabean      3. Madhya Pradesh",
    "D. Coconut        4. Kerala",
    "Codes: A B C D",
    "(a) 1 3 2 4",
    "(b) 2 1 3 4",
    "(c) 1 2 3 4",
    "(d) 4 3 2 1",
    "U.P .P .C.S. (Mains) 2008",
    "Answer - (c)",
    "",
"28. Evaluate the correlation between these Historical Figures and their contributions: [2020]",
    "List-I (Figure)                List-II (Contribution)",
    "A. Leonardo da Vinci       1. Theory of Relativity",
    "B. Isaac Newton                2. Mona Lisa",
    "C. Albert Einstein             3. Laws of Motion",
    "D. Marie Curie                   4. Radioactivity Discovery",
    "Codes: A B C D",
    "(a) 2 3 1 4",
    "(b) 3 2 4 1",
    "(c) 2 3 4 1",
    "(d) 1 4 2 3",
    "U.P.S.C. (Mains) 2020",
    "Answer - (a)",
    "",
    "29. Match the following Rivers with the cities they flow through: [2021]",
    "List-I (River)              List-II (City)",
    "A. Thames               1. Paris",
    "B. Seine                 2. London",
    "C. Danube               3. Vienna",
    "D. Nile                  4. Cairo",
    "Codes: A B C D",
    "(a) 2 1 3 4",
    "(b) 1 2 4 3",
    "(c) 3 4 1 2",
    "(d) 4 3 2 1",
    "U.P.S.C. (Mains) 2021",
    "Answer - (a)",
    "",
    "30. Associate these Books with their Authors: [2019]",
    "List-I (Book)                      List-II (Author)",
    "A. 1984                               1. Mark Twain",
    "B. Adventures of Huckleberry Finn  2. George Orwell",
    "C. To Kill a Mockingbird            3. Harper Lee",
    "D. The Great Gatsby                 4. F. Scott Fitzgerald",
    "Codes: A B C D",
    "(a) 2 1 3 4",
    "(b) 3 4 2 1",
    "(c) 1 2 4 3",
    "(d) 2 1 3 4",
    "U.P.S.C. (Mains) 2019",
    "Answer - (d)",
    "",
    "31. Connect these Elements with their Chemical Symbols: [2022]",
    "List-I (Element)            List-II (Symbol)",
    "A. Hydrogen                  1. O",
    "B. Oxygen                    2. H",
    "C. Gold                      3. Au",
    "D. Silver                    4. Ag",
    "Codes: A B C D",
    "(a) 2 1 3 4",
    "(b) 1 2 4 3",
    "(c) 3 4 1 2",
    "(d) 4 3 2 1",
    "U.P.S.C. (Mains) 2022",
    "Answer - (a)",
    "",
    "32. Link the following Philosophers with their Philosophies: [2018]",
    "List-I (Philosopher)      List-II (Philosophy)",
    "A. Plato                      1. Existentialism",
    "B. Aristotle                  2. Empiricism",
    "C. Sartre                     3. Realism",
    "D. Locke                     4. Idealism",
    "Codes: A B C D",
    "(a) 4 3 1 2",
    "(b) 3 4 2 1",
    "(c) 2 1 4 3",
    "(d) 1 2 3 4",
    "U.P.S.C. (Mains) 2018",
    "Answer - (a)",
    "",
    "33. Correlate these Countries with their Capitals: [2023]",
    "List-I (Country)           List-II (Capital)",
    "A. Australia                 1. Ottawa",
    "B. Canada                    2. Canberra",
    "C. Japan                     3. Tokyo",
    "D. Brazil                    4. Brasília",
    "Codes: A B C D",
    "(a) 2 1 3 4",
    "(b) 1 2 4 3",
    "(c) 3 4 1 2",
    "U.P.S.C. (Mains) 2019",
    "Answer - (a)",
    "",
    # Additional questions to be added here...
]

# Add each question to the document
for question in questions:
    para = doc.add_paragraph()
    para.add_run(question).bold = False

# Save the document
doc_path = 'Generated_Questions.docx'
doc.save(doc_path)

print(doc_path)
